### ISSUE TITLE
Suspected memleak in Chrome

### ISSUE THREAD

**Issue by beaverdude** [artemtam/cyber-yozh#7] opened 2022-02-28 23:46 UTC
Win10, Win11, the latest clean chrome, no extensions.
Memory which is allocated to chrome process constantly grows and eventually Windows kills the process (or chrome tab self-crashes)
More threads I select - faster an OOM happens. 

Does anyone see same behavior?

**Comment by artemtam** [comment] 2022-03-01 00:36
I've seen some reports, so most likely the issue is valid. 
Any ideas where it could be?

**Comment by beaverdude** [comment] 2022-03-01 06:11
yeah, I suspect that's the effect of increased size of Promises (with arguments) in an array due to added payload. 
It looks like a chrome's garbage collector doesn't cleanup after a promise is resolved/rejected and shifted out from an array, or maybe doesn't do it quickly enough. 
For the test I increased a payload size to 200kB and got OOM in a matter of minutes.

**Comment by artemtam** [comment] 2022-03-01 08:45
Fixed in #8.

**Closed as completed by artemtam** 2022-03-01 08:45 UTC
